theme: jekyll-theme-minimal

# https://github.com/pages-themes/minimal

title: Hospitality Camp
email: hospexsummit@gmail.com
description: We strive to federate different hospitality exchange platforms to unify the community and enable greater diversity and long term sustainability of all together.
baseurl: ''
url: https://fedihospex.github.io
#twitter_username: Your Twitter username (do not include @ symbol).
github_username: FediHospEx
google_analytics: UA-199347194-1

markdown: kramdown
kramdown:
  input: GFM

plugins:
    - jekyll-seo-tag
