theme: jekyll-theme-minimal

# https://github.com/pages-themes/minimal

title: Open Hospitality Network
email: hospexsummit@gmail.com
description: FediHospEx strives to federate different hospitality exchange platforms to unify diverse communities and ensure long term sustainability and resilience.
baseurl: ''
url: https://fedihospex.github.io
#twitter_username: Your Twitter username (do not include @ symbol).
github_username: FediHospEx
google_analytics: UA-199347194-1

markdown: kramdown
kramdown:
  input: GFM

plugins:
    - jekyll-seo-tag
